Projects/mysite/accueil/urls.py
from django.urls import path

from . import views

app_name = 'accueil'

urlpatterns = [
    path('',views.index, name ='index'),
]

Projects/mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # chaque Apps Url
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('', include('accueil.urls')),
]

Projects/mysite/pybo/urls.py
from django.urls import path

from . import views

app_name = 'pybo'

urlpatterns = [
    path('',views.index, name ='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
]

Projects/mysite/accueil/models.py
from django.db import models

# Create your models here.

Projects/mysite/pybo/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.content

Projects/mysite/pybo/forms.py
from django import forms

from pybo.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        labels = {
            'subject': '제목',
            'content': '내용',
        }


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

Projects/mysite/accueil/views.py
from django.shortcuts import render

# Create your views here.
def index(request):

    return render(request, 'accueil/accueil.html')

Projects/mysite/pybo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Question
''', Answer'''
from .forms import QuestionForm, AnswerForm

def index(request):
    """
    pybo 목록 출력
    """

    question_list = Question.objects.order_by('-create_date')
    context = {'question_list' : question_list}
    return render(request, 'pybo/question_list.html', context)

def detail(request, question_id):
    '''
    pybo 내용 출력
    '''

    question = get_object_or_404(Question, pk=question_id)
    context = {'question':question}
    return render(request, 'pybo/question_detail.html', context)

def answer_create(request, question_id):
    '''
    pybo 답변 등록
    '''

    question = get_object_or_404(Question,pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False) # 임시저장
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)

    ''' 또 다른 방법. 가장 제일 위에 Answer 꼭 넣어야 함 
    question = get_object_or_404(Question, pk=question_id)
    answer = Answer(question=question, content=request.POST.get('content), create_date = timezone.now())
    answer.save()
    return redirect('pybo:detail', question_id=question.id)
    '''

def question_create(request):
    '''
    pybo 질문 등록
    '''
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False) # 임시저장
            question.create_date = timezone.now()
            question.save() # 완전히 저장
            return redirect('pybo:index') # 저장 후 다시 원래 화면으로 돌아감
    else: # GET일 때
        form = QuestionForm()

    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

Projects/mysite/templates/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Osiris Web</title>

    <!-- icon -->
    <link rel="shortcut icon" href="/static/img/icon.png" size="200x200" type="image/x-icon">
    <link rel="icon" href="/static/img/icon.png"  size="200x200" type="image/x-icon">

    <!--  Bootstrap css file  -->
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">

    <!--  font awesome icons  -->
    <script src="https://kit.fontawesome.com/da11f279bc.js" crossorigin="anonymous"></script>

    <!--  Magnific Popup css file  -->
    <link rel="stylesheet" href="{% static 'magnific-popup.css'%}">


    <!--  Owl-carousel css file  -->
    <link rel="stylesheet" href="{% static 'owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static  'owl.theme.default.min.css' %}">

    <!--  custom css file  -->
    <link rel="stylesheet" href="{% static 'style.css' %}">

    <!--  Responsive css file  -->
    <link rel="stylesheet" href="{% static 'responsive.css' %}">

</head>
<body>
    {% include "navbar.html" %}


    {% block content %}
    {% endblock%}



    {% include "footer.html" %}


    <!--  Jquery js file  -->
    <script src="{% static 'jquery.3.4.1.js' %}"></script>

    <!--  Bootstrap js file  -->
    <script src="{% static 'bootstrap.min.js' %}"></script>

    <!--  isotope js library  -->
    <script src="{% static 'isotope.min.js' %}"></script>

    <!--  Magnific popup script file  -->
    <script src="{% static 'jquery.magnific-popup.min.js' %}"></script>

    <!--  Owl-carousel js file  -->
    <script src="{% static 'owl.carousel.min.js' %}"></script>

    <!--  custom js file  -->
    <script src="{% static 'main.js' %}"></script>

</body>

</html>

Projects/mysite/templates/footer.html
{% load static%}
    <footer class="footer-area">
        <div class="container">
            <div class="">
                <div class="site-logo text-center py-4">
                    <a href="#"><img src="/static/img/logo.png" alt="logo"></a>
                </div>
                <div class="social text-center">
                    <a href="#" style="color:#f2b680;"><i class="fab fa-facebook" style="color:#f2b680"></i>Facebook</a>
                    <a href="#" style="color:#f2b680;"><i class="fab fa-linkedin" style="color:#f2b680"></i>LinkedIn</a>

                </div>
                <div class="copyrights text-center">
                    <p class="para" style="color:#f2b680;">
                        Copyright ©2021 All rights reserved <span style="color: #ffffff;">Osiris Web</span></a>
                    </p>
                </div>
            </div>
        </div>
    </footer>

Projects/mysite/templates/navbar.html
{% load static%}
    <!--  ======================= Start Header Area ============================== -->
    <header class="header_area">
        <div class="main-menu" id="navnav">
            <nav class="navbar navbar-expand-lg" style="padding: 0px;">
                <a class="navbar-brand" href="#"><img src="/static/img/logo.png" alt="logo"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <div class="mr-auto"></div>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="#Contact" >Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#" id="News">News</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </header>
    <!--  ======================= End Header Area ============================== -->

Projects/mysite/templates/pybo/question_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ question.create_date }}
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ answer.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
        {% endfor %}
        </div>
        {% endif %}
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}

Projects/mysite/templates/pybo/question_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        <!--{{ form.as_p }} # forms.py에 있는 form의 속성에 관한 것들이 자동으로 HTML 코드로 생성 -->
        <!-- 오류표시 Start : 아무 것도 적지 않았을 때-->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

Projects/mysite/templates/pybo/question_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                <a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
            </td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록하기</a>

</div>
{% endblock %}